name: Publish NuGet Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# on:
#   push:
#     tags:
#     - 'v*'

env:
  PROJECT_PATH: ./src/ParticleSwarmSharp/ParticleSwarmSharp.csproj
  PACKAGE_OUTPUT_PATH: ${{ github.workspace }}\output

jobs:
  build:
    name: Publish NuGet Package
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build
      run: dotnet build --no-restore ${{ env.PROJECT_PATH }}

    - name: Get version
      id: get_version
      uses: battila7/get-version-action@v2

    - name: Pack
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=0.1 --output ${{ env.PACKAGE_OUTPUT_PATH }}
# run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.get_version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_PATH }}
      working-directory: ${{ env.PROJECT_PATH }}
